### ISSUE TITLE
Can't install on MacOS 11.2.3

### ISSUE THREAD

**Issue by CulturalClub** [wilddom/memrise2anki-extension#100]
Followed the steps, but after app restart add-on list is empty being added to ⁨Anki. Can you check it please?

    Debug info:

    Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.16
    Flags: frz=True ao=False sv=2
    Add-ons, last update check: 2021-04-25 13:35:27
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by wilddom** [comment]
It's difficult to say without knowing more details, most likely you copied it to the wrong folder.
