### ISSUE TITLE
An add-on you installed failed to load.

### ISSUE THREAD

**Issue by cpsneto** [wilddom/memrise2anki-extension#104]
I received this message after following the manual installation and restarting Anki:
"An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨memrise2anki-extension-1.2.6⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
ModuleNotFoundError: No module named 'memrise2anki-extension-1' "
⁩
How to solve this issue?

**Comment by wilddom** [comment]
Just rename the directory to 'memrise2anki'
