### ISSUE TITLE
error line 214, 840!!

### ISSUE THREAD

**Issue by HaiDuongdarkocean** [wilddom/memrise2anki-extension#107]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-12-06 11:14:34

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ngocg\AppData\Roaming\Anki2\addons21\memrise2anki-extension\importer.py", line 214, in accept
    if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()):
  File "C:\Users\ngocg\AppData\Roaming\Anki2\addons21\memrise2anki-extension\memrise.py", line 840, in login
    for field in form.find_all("input"):
AttributeError: 'NoneType' object has no attribute 'find_all'

I hope you fix this!! thank you 3000 :">

**Comment by Kbobous** [comment]
Yeah I have the same problem.I really hope that it's fixed before the old memrise vanishes.It's literally the best addon for anki :D

**Comment by adrian225** [comment]
Same here. Not sure what you mean about old memrise, but yes. You can't upload decks that are big in size on Anki so a lot of the decks on it are pretty minimalistic and don't have large data the way Memrise is able to do things.

**Comment by Kbobous** [comment]
Ah I mean what's written when you are on the memrise dashboard
"From 31st December 2021 we'll be retiring our classic learning sessions and homepage and moving to our redesigned and improved learning platform. All your courses will still be there for you to keep learning. If you want to try it out earlier, you can turn on the new version in your account settings."
I have no programming skills, so I am not sure if the addon is completely broken after that or if it still just needs a small fix.

**Comment by YpeZ** [comment]
I got the same error and tried looking into it. 
It seems like the html the program encounters is different from the page source I get when looking at view-source:https://app.memrise.com/login/, but couldn't figure out how to get that correct

**Comment by wilddom** [comment]
See #103
