### ISSUE TITLE
Getting a 403 error

### ISSUE THREAD

**Issue by wilddom** [wilddom/memrise2anki-extension#11]
Getting a 403 error while attempting to import

http://www.memrise.com/course/58866/5000-words-sorted-by-frequency-strict-typing/

Error occurs after downloading approximately 5 percent of course

```
"C:\Users\Paul\Documents\Anki\addons\Memrise_Course_Importer\importer.py", line 395, in importCourse 
    raise self.loader.getError() 
urllib2.HTTPError: HTTP Error 403: Forbidden
```

https://anki.tenderapp.com/discussions/add-ons/1215-memrise-course-importer#comment_35303087

**Comment by cherryleafroad** [comment]
Hi, regarding this bug, I tried to download a deck that came up with the error, then I went through the deck on the website and found this out.

The plugin requested the path,
`http://static.memrise.com/static/uploads/mems/32000100826111644.gif`

The actual path for the image was,
`http://static.memrise.com/uploads/mems/32000100826111644.gif`
