### ISSUE TITLE
Unable to download after 31 Dec 2021 website changes

### ISSUE THREAD

**Issue by Onabotulinumtoxin-A** [wilddom/memrise2anki-extension#111]
I'm able to download the most updated addon version and upload it to Anki, but I'm getting a similar error to most when I try to download a deck. Once the download completes, I get an error found throughout many older issues along the lines of Issue #89:

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart 
> Debug info:
> Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
> Platform: Windows 10
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-10-05 00:02:12

I tried all the solutions mentioned in older issues, but I noticed that Memrise redesigned their learning platform on 31 Dec 2021. Would the changes on the website itself cause issues for brand new addon users such as myself?

**Comment by wilddom** [comment]
Try updating anki, the latest version is 2.1.49, there is in fact an incompatibility with older versions of anki, see #110 #108
