### ISSUE TITLE
'Invalid Credentials' 

### ISSUE THREAD

**Issue by blyn126** [wilddom/memrise2anki-extension#112]
I get an invalid credentials notification when I try to log into Memrise through the extension, but I know it's the right username and password. 

If I try to enter my information a second time I get an error message.

Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-21 20:38:51
Add-ons possibly involved: ⁨memrise2anki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/*******/Library/Application Support/Anki2/addons21/2071525018/importer.py", line 210, in accept
    if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()):
  File "/Users/*******/Library/Application Support/Anki2/addons21/2071525018/memrise.py", line 773, in login
    for field in form.find_all("input"):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by wilddom** [comment]
You are using an old version of the addon, please try the [1.2.7](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.7) release.
