### ISSUE TITLE
Fehler   importer.py", line 856,      line 151,   memrise.py", line 870     line 623

### ISSUE THREAD

**Issue by nartererol** [wilddom/memrise2anki-extension#114]
Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.49 (dc80804a) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-05-31 20:40:06
Möglicherweise beteiligte Erweiterungen: ⁨memrise2anki⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/memrise2anki/importer.py", line 856, in importCourse
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
  File "/home/user/.local/share/Anki2/addons21/memrise2anki/importer.py", line 151, in run
    course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
  File "/home/user/.local/share/Anki2/addons21/memrise2anki/memrise.py", line 870, in loadCourse
    return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
  File "/home/user/.local/share/Anki2/addons21/memrise2anki/memrise.py", line 623, in loadCourse
    course.title = sanitizeName(courseData["session"]["course"]["name"], "Course")
TypeError: 'NoneType' object is not subscriptable

**Comment by wilddom** [comment]
See #113
