### ISSUE TITLE
Error when trying to Import Memrise Deck

### ISSUE THREAD

**Issue by b34ni** [wilddom/memrise2anki-extension#117]
I wasn't able to import a deck. This is the debug info:

Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-29 09:21:58
Add-ons possibly involved: ⁨memrise2anki⁩

**Comment by wilddom** [comment]
See  #113
