### ISSUE TITLE
Will this extension import my mems from memrise?

### ISSUE THREAD

**Issue by olliebaum** [wilddom/memrise2anki-extension#22]
This extension says it can import a course from memrise, but does it currently allow you to import your mems from memrise? (Mems are the notes you create to help you learn and remember the information.)

**Comment by wilddom** [comment]
No, the add-on does not import mems at the moment. I'll look into it, no promises though.

**Comment by olliebaum** [comment]
Thanks, it would be really cool if you did. Then any chosen mems could be
added to the back of a card to help you remember it better for next time.

**Comment by wilddom** [comment]
I have implemented support for mems now. But it's not heavily tested...

**Comment by olliebaum** [comment]
That's really great! Thanks for all your hard work. I'll test it out later
and hopefully I can let you know if anything is not working.
Just so I know, how have you implemented it? What should I expect to see?
I'm expecting it to only import the mems I've selected.

**Comment by wilddom** [comment]
Well, there is now a checkbox which controls the mem import. I suppose you have already imported the course without mems. In that case you can update your existing deck, just open the import screen again and select the existing deck. But before doing that you would have to edit the existing note type manually and add a field for the mems. Later on in the import procedure you will be asked to assign this field. And of course afterwards you would have to edit the template too. It's recommended to take a backup of your collection before doing this.

**Comment by olliebaum** [comment]
If I update my existing deck will it overwrite my anki progress?

**Comment by wilddom** [comment]
Just make sure the "Import scheduler information" checkbox is deactivated.

**Comment by olliebaum** [comment]
There are two new field types - “Mem: artist" and “Mem: none”. Do I need to
add field for them both?

**Comment by olliebaum** [comment]
I’m getting this error when I try and update a deck:

Traceback (most recent call last):

File
"/Users/ollie/Documents/Anki/addons/Memrise_Course_Importer/importer.py",
line 777, in importCourse

values.extend(self.toList(self.getWithSpec(thing, spec)))

File
"/Users/ollie/Documents/Anki/addons/Memrise_Course_Importer/importer.py",
line 720, in getWithSpec

if values.isTextMem():

AttributeError: 'NoneType' object has no attribute 'isTextMem'

**Comment by wilddom** [comment]
Could you tell me the course url?

**Comment by olliebaum** [comment]
Sure. It’s http://www.memrise.com/course/54535/who-composed-me/

**Comment by wilddom** [comment]
Well... I found some things:
1. The bug you mentioned is fixed.
2. There is a strange bug in the data from memrise. Actually a mem should only be valid for one testing direction (Front->Back), but in this course I get an invalid testing direction (column 0->column 0). So I had to implement a workaround which will unfortunately not work perfectly.
3. I didn't know mems can mix text and images. So there is still some work to do for complex mems. Simple text and images should work.

**Comment by olliebaum** [comment]
Okay, thanks. I’ll give it another try and see what happens.

**Comment by wilddom** [comment]
I'll need to implement some kind of Markdown syntax:
http://memrise-users.wikia.com/wiki/Mems_Formatting_Feature
Additionally there is an undocumented syntax for images: "img:[url]"

**Comment by olliebaum** [comment]
Thanks. It seems to be be working pretty well for me now.

- The mems I selected or created have all been imported and I can see them
in the ‘mem’ field I created.
- The image+text mems I created are showing up for me so that’s not a
problem.
- The only thing I noticed is that for text mems the formatting is
incorrect. I get extra *s and bold text formatting incorrectly. So if you
implement Markdown syntax this will probably solve itself.
- Oh, and embedded videos don’t show up. But I wasn’t expecting that if I’m
honest! (Memrise has an "embed:[url]” syntax for embedding youtube videos
and vines.)

But this is still really amazing! Nice job.

**Comment by wilddom** [comment]
Thank you for the feedback.
* Yes, I have noticed that the syntax for bold text is wrong, this will be fixed with the Markdown parser I'm planning to integrate, so I thought it's not worth fixing it.
* Videos... wow. Well, downloading videos form youtube etc. is not really within the scope of this addon. And as it's not possible to embed external videos using html5/flash, a link is maybe the best option.

**Comment by olliebaum** [comment]
Well

**Comment by olliebaum** [comment]
Well currently it shows "embed:[my youtube url]". If it just showed a link
instead that would be great. If it helps - I think memrise uses embed.ly to
embed any content linked using the "embed:" syntax. The embed.ly api
fetches the html embed code and adds it in-line. But yeah as I said, just a
link would be fine.

**Comment by olliebaum** [comment]
Apparently you can use oembed <http://www.oembed.com> to return an embed
code for a URL. It has a python library too.
But the problem is I tried putting some embed code in a field but Anki just
shows the code and not the video. (If you paste the embed code directly
into the card’s HTML, it works.)

**Comment by wilddom** [comment]
Okay, but as Anki officially does not support such embed codes (iframes, etc.), it seems a bit "hackish".

**Comment by wilddom** [comment]
I just noticed that I misinterpreted memrise's data, so it's possible that wrong mems were imported. But that's fixed now and so is bold formatting. Next step is full Markdown support.

**Comment by wilddom** [comment]
Now we have full Markdown support for mems. Embedded media using embed:[url] will be converted to a link.

**Comment by wilddom** [comment]
And now there is an option to embed online media (disabled by default).

**Comment by olliebaum** [comment]
This is great! The embedding online media is working great for me. I noticed one small problem - if there's a space between "embed:" and the URL then the embed doesn't work and it just generates a link.

**Comment by wilddom** [comment]
Okay, should be more tolerant to spaces now.
