### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type RunnableWrapper has been deleted

### ISSUE THREAD

**Issue by cherryleafroad** [wilddom/memrise2anki-extension#26]
1. Go to Tools->Import Memrise Course...
2. Paste in URL of a course without image mems.*
3. Keep "Import Mems" checked.
4. Press OK.
5. It should fail with 403 error. Click Abort.
6. Press OK again, and I get an error.

To fix problem, close dialog and reopen it again.

* I used http://www.memrise.com/course/47843/common-simplified-chinese-radicals/

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "D:\Users\user\Documents\Anki\addons\Memrise_Course_Importer\importer.py", line 904, in loadCourse
    self.loader.start(courseUrl)
  File "D:\Users\user\Documents\Anki\addons\Memrise_Course_Importer\importer.py", line 128, in start
    QThreadPool.globalInstance().start(self.runnable)
RuntimeError: wrapped C/C++ object of type RunnableWrapper has been deleted
```

**Comment by cherryleafroad** [comment]
Maybe it's also a good time to make a note that the mems are failing to download in the first place, which is why I clicked Abort to begin with. Here's an example of the URL it failed with with a 403 error, (same course as listed above).

```
---------------------------
Download failed
---------------------------
HTTP Error 403: Forbidden
---------------------------
http://static.memrise.com/static/uploads/mems/32000100726085433.gif
---------------------------
Retry   Ignore   Abort   Hide Details...   
---------------------------
```

**Comment by wilddom** [comment]
Thanks for reporting, it should be fixed now. But regarding the 403 errors... I don't really know how to prevent them (see #11).
