### ISSUE TITLE
Downloads broken

### ISSUE THREAD

**Issue by cherryleafroad** [wilddom/memrise2anki-extension#27]
After your last commit to fix #26 :/ , downloads no longer work. It just sits there at 0%. I tested without the change, and downloading works properly without the commit for issue #26.

**Comment by cherryleafroad** [comment]
Never mind, seems to have been something else.

**Comment by wilddom** [comment]
I can't reproduce, working fine here. What is your exact setup?

**Comment by wilddom** [comment]
This bug did occur on Windows only.
