### ISSUE TITLE
Plugin continues working in background after window is closed

### ISSUE THREAD

**Issue by cherryleafroad** [wilddom/memrise2anki-extension#28]
I put some popup code in one of the calls, and found out that the plugin continues to operate in the background even after clicking the red X to close the window. Perhaps there's some way to abort the running task if the window gets closed, or keep the window from being closed and provide a Quit button in the UI.

**Comment by wilddom** [comment]
Nice one ;) I will need to have a closer look into the Qt api.

**Comment by wilddom** [comment]
Do you have a close button in the title bar of that dialog?

**Comment by cherryleafroad** [comment]
Yes, I see a close button in the title bar. I am using Windows 10.
![capture](https://cloud.githubusercontent.com/assets/13651622/10458559/36ee2c94-7180-11e5-884c-23e963c5de49.PNG)

**Comment by cherryleafroad** [comment]
Confirmed. Your latest commit prevents closing the dialog when it's running.
