### ISSUE TITLE
Image 403 errors

### ISSUE THREAD

**Issue by cherryleafroad** [wilddom/memrise2anki-extension#29]
I made a comment in issue #11 about your 403 errors, however I felt that this specific issue regarding image 403 errors needed its own new issue for clarification purposes. Feel free to merge or delete this issue if you would rather follow #11 

---

I tried to download a deck that came up with the 403 image error, then I went through the deck on the website and found this out.

For all images with 403 errors reported by the plugin, the paths were in the following format,
`http://static.memrise.com/static/uploads/mems/32000100826111644.gif`

But the actual paths were, (omitting `/static/`)
`http://static.memrise.com/uploads/mems/32000100826111644.gif`

The course I used for testing was,
`http://www.memrise.com/course/749/introductory-chinese-read-a-menu-no-audio/`

Why some of the images have correct paths and download, while others don't, I am not sure, but there is definitely a problem. It's probably :100:% fixable, thankfully.

**Comment by wilddom** [comment]
Thank you for looking into it. The urls are now fixed before trying to download, this should work unless they really have valid resources in /static/. But I suppose that's highly unlikely.
