### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by TheSuitIsNotBlack** [wilddom/memrise2anki-extension#31]

**Comment by wilddom** [comment]
1. Download the ZIP-File from github.
2. Open Anki
3. Click on Tools -> Add-ons -> Open Add-ons Folder...
4. Extract the ZIP-File (content of memrise2anki-extension-master) in that folder

**Comment by TheSuitIsNotBlack** [comment]
That didn't work, but I found out how to get it to work. I had to install the addon from anki's site first, then overwrite the files with yours.

**Comment by wilddom** [comment]
Oh, I forgot step 5:
5. Restart Anki
