### ISSUE TITLE
Unable to import one particuliar Memrise course

### ISSUE THREAD

**Issue by mtthth** [wilddom/memrise2anki-extension#33]
Hello,

First of all, thank you for your invaluable addon, I used it  umpteenth  time !

Notwithstandig, I'm not able to import this particuliar course : http://www.memrise.com/course/700010/easy-university-history/.

Download seems OK, but only ten cards (instead of 10000+) are successfuly imported.

Thank for any advice.

**Comment by wilddom** [comment]
Oookay, that course has a huge number of columns and attributes with some very long and strange names. There are even multiple unicode byte order marks in the middle of the course title.
