### ISSUE TITLE
"Minimal level tag width filled width zeros:"?

### ISSUE THREAD

**Issue by lagleki** [wilddom/memrise2anki-extension#36]
I can't parse this phrase. Is it even grammatical?
https://github.com/wilddom/memrise2anki-extension/blob/master/Memrise_Course_Importer/importer.py#L673

**Comment by wilddom** [comment]
Well, I admit it's a very technical description I wanted to replace later... and there is even a typo, the second "width" should be "with". It actually should describe the padding of level numbers:

E.g.
1: Level1, ..., Level9, Level10, ..., Level99, Level 100
2: Level01, ..., Level09, Level10, ..., Level99, Level 100
3: Level001, ..., Level009, Level010, ..., Level099, Level 100

Any suggestions for a comprehensible and concise description?
