### ISSUE TITLE
please update the addon on Ankiweb (memrise has switched to https - login fails)

### ISSUE THREAD

**Issue by tpo** [wilddom/memrise2anki-extension#42]
Hi wilddom,

thanks a lot for your importer.

It seems that in the meantime Memrise has switched from http to https:

```
> ~/Documents/Anki/addons/Memrise_Course_Importer/memrise.py(749)login()
    748         response2 = self.openWithRetry(request2)
--> 749         return response2.geturl() == 'http://www.memrise.com/home/'
    750 

ipdb> response2.geturl()
'https://www.memrise.com/home/'
```

which makes the login procedure in the memrise2anki-extension addon fail (line 749 will evaluate to `False`).

Replacing `http` with `https` on line 749 fixes the immediate problem, however similar problems pop up further down along the code execution path. I.e. on line 655 of importer.py the dialog requests the URL of the Memrise course and suggests and expects a http (without an 's') address exclusively. If given a https address the dialogue will not switch the "OK" (proceed...) button from greyed out to active. 

There are many reports on your Anki addons page (https://ankiweb.net/shared/info/889633840) reporting that login problem, so a little s/http/https/ should fix that...

**Comment by tpo** [comment]
Oh! For some reason AnkiHub had failed to update the code to the current github version of your plugin and I was looking at old code while debugging.

Indeed you have allready fixed the http/s problem.

Could please update the addon on Ankiweb so that people can again  successfully use it?

**Comment by wilddom** [comment]
The thing is, I am not the original author, I just took over the apparently abandoned project, that's why there can be found two old memrise importer addons in anki's catalog at the moment. Both submitted by other people, therefore I can't update them. And I don't really want to submit a third "even newer" version. But I'll try to get in touch with anki's staff.

**Comment by wilddom** [comment]
https://ankiweb.net/shared/info/1340350102

**Comment by tpo** [comment]
Thanks a lot wilddom!

**Comment by tpo** [comment]
I have seen that the ankiweb maintainers have deleted the other, old, non-working importers. Very good! Again: many thanks @wilddom!
