### ISSUE TITLE
ValueError on loadScheduleInfo in memrise.py

### ISSUE THREAD

**Issue by moniquemurphy** [wilddom/memrise2anki-extension#46]
I got a ValueError: unconverted data remains: Z on line 601 of memrise.py. I was able to fix it with try/except block on scheduleInfo.due, but not sure if this is the best long-term solution. It looks like imported dates on Memrise might not always be formatted the same way.

**Comment by wilddom** [comment]
Hm... well, are you sure you do have the latest version installed? I think the same error has been reported (#45) and fixed (854e54750efb9db57891a72a5bb7f4d4240568c7) in May.
