### ISSUE TITLE
Cant load courses

### ISSUE THREAD

**Issue by HPLT** [wilddom/memrise2anki-extension#47]
Hi wilddom,

thanks for your extensive work on this addon. However, recently I faced an error and can't load courses (see log below). 

I tried multiple version of your extension (all available) as well as different Anki versions (2.1 Beta, 2.0.47, 2.0.44, 2.0.36)

Maybe you can help me out :-)

Cheers Max 

> An error occurred in an add-on.
> Please post on the add-on forum:
> https://anki.tenderapp.com/discussions/add-ons
> 
> Traceback (most recent call last):
>   File "C:\Users\Max\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\importer.py", line 146, in run
>     course = self.memriseService.loadCourse(self.url, MemriseCourseLoader.Observer(self))
>   File "C:\Users\Max\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 779, in loadCourse
>     return courseLoader.loadCourse(self.getCourseIdFromUrl(url))
>   File "C:\Users\Max\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 579, in loadCourse
>     level = self.loadLevel(course, levelIndex)
>   File "C:\Users\Max\AppData\Roaming\Anki2\addons\Memrise_Course_Importer\memrise.py", line 640, in loadLevel
>     if levelData["success"] == False:
> KeyError: 'success'

**Comment by wilddom** [comment]
Well, memrise changed the data format again. I'll have to take a closer look as soon as I find the time.

**Comment by HPLT** [comment]
Hey Wilddom,

thanks for your message. I was assuming that :-)

Cheers Max

**Comment by CableGuy67** [comment]
Thanks for the fix. It's an amazingly helpful addon. Cheers.
