### ISSUE TITLE
Adapt to latest webservice changes

### ISSUE THREAD

**Issue by wilddom** [wilddom/memrise2anki-extension#49]
Memrise again changed the data of their webservice...

https://anki.tenderapp.com/discussions/add-ons/13507-memrisecourseimporter-keyerror-pools

**Comment by wilddom** [comment]
https://anki.tenderapp.com/discussions/add-ons/13507-memrisecourseimporter-keyerror-pools

**Comment by wilddom** [comment]
https://www.memrise.com/api/pool/get/?pool_id=xyz
https://www.memrise.com/api/thing/get/?thing_id=xyz

**Comment by voylin** [comment]
I wanted to try this add-on last month and noticed the error. Today I tried to see it got fixed and I came across this. How is the fixing of this error going? :o

**Comment by wilddom** [comment]
I looked into it and I think I know how to fix it, but unfortunately I'm still too busy with other things.

**Comment by wilddom** [comment]
Can someone please test the current master branch? It should work now, but it's not extensively tested. And unfortunately it's a slower now, because of the changed api we have to send a lot of web requests.

**Comment by voylin** [comment]
it's slow but it's working for sure, not completed yet but I'm sure it'll complete successfully, thanks ^o^

**Comment by v11viktor** [comment]
It works very well. Thank you.

**Comment by BaneOfRome** [comment]
Works for me. Thank you for the continued support!
