### ISSUE TITLE
Download videos (Learning with locals)

### ISSUE THREAD

**Issue by LukeeB** [wilddom/memrise2anki-extension#58]
It would be perfect if this add-on could download also video files (learning with locals videos) to anki and attach them to corresponding flashcards. Is this actually possible?

**Comment by wilddom** [comment]
Hm... this feature is exclusive to pro users and only available in the app, isn't it?

**Comment by Neribr** [comment]
The other day I tried out the french course; the mini-videos are available on the computer version, and for free.

This is a rather recent change: the free oficial courses are very full of mini-video files of locals speaking, which is pretty cool.

**Comment by tamueller** [comment]
In the free version you only get them in the learning phase (at least in German->Spanish course). There is a function "learn with locals" that allows you to repeat words with those videos, but its only available in the pro version.

You could either download them, by learning a course from scratch, or if the user has the pro version.

**Comment by wilddom** [comment]
But I'm pretty sure the videos are copyrighted content, so...

**Comment by wilddom** [comment]
Memrise is moving all user contributed courses to a new website called Decks. And downloading your own courses has always been the sole intention of this addon. Therefore the addon will switch to Decks and won't support downloading official courses from the future Memrise website, I'm afraid.
