### ISSUE TITLE
Failing to pull in all of the course?

### ISSUE THREAD

**Issue by peripatew** [wilddom/memrise2anki-extension#59]
Greetings!

First, thanks for working on this extension.  It's fantastic!  I am however having a bit of a problem, in that it is only pulling in 22 out of 50 Lessons within a particular course.  If I attempt to update it, it doesn't seem to resume from where it left off.

Any thoughts?

**Comment by wilddom** [comment]
Could you please provide the course url?

**Comment by peripatew** [comment]
https://www.memrise.com/course/931056/khmer-vocabulary-by-frequency-top-1000-words/ [https://www.memrise.com/course/931056/khmer-vocabulary-by-frequency-top-1000-words/]

L!
On Wed, Jan 31, 2018 at 4:34 PM, wilddom <notifications@github.com> wrote:
Could you please provide the course url?

**Comment by wilddom** [comment]
Confirmed. But I even get "Could not load session" when trying to learn levels 23-51 using the web interface. There must be something wrong on memrise's side...

**Comment by peripatew** [comment]
Ah, I see now that those lessons have “incomplete” in the title, I’m assuming because the audio isn’t uploaded/finished. Is there anything in the code that is looking for “complete”? The lessons have complete vocab/definitions, which would be good for me to be able to pull also?
Thanks for being responsive.

On Thu, Feb 1, 2018 at 9:41 PM, wilddom <notifications@github.com> wrote:
Confirmed. But I even get "Could not load session" when trying to learn levels 23-51 using the web interface. There must be something wrong on memrise's side...

**Comment by wilddom** [comment]
Unfortunately there is no way to load the definitions, trying to load one of the incomplete levels ends in an error. Just try clicking on "Learn" and you should get: "Whoops. Could not load the session. Sorry."
