### ISSUE TITLE
Split multiple sounds in different columns

### ISSUE THREAD

**Issue by tamueller** [wilddom/memrise2anki-extension#60]
Hi,
in the courses I'm using there are always two audio files, a male and a female version. Currently, I hear them both when I add the audio column, and I couldn't find a way to play only one of the audio files.

So, it would be cool, if you could either split the audios in two columns or point me to an HOW-TO for playing only one audio file.

**Comment by wilddom** [comment]
By default columns are imported the way they were created by the author of the memrise course. In your case I think both audio files are contained in one column even on memrise. Splitting columns is beyond the scope of this add-on, I'm afraid. But there is an article about how to split fields in the anki knowledge base:
https://anki.tenderapp.com/kb/collection-management/splitting-a-field-into-multiple-fields

**Comment by tamueller** [comment]
Hi, thanks for the fast response - that link was helpfull enough, I can split the course with that on my own!
