### ISSUE TITLE
Any plan to support Anki 2.1.x?

### ISSUE THREAD

**Issue by x-ji** [wilddom/memrise2anki-extension#61]
Got an error while trying to use the plugin today.

```python
When loading 'Memrise_Course_Importer':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 60, in loadAddons
    __import__(dir)
  File "/home/jx/.local/share/Anki2/addons21/Memrise_Course_Importer/__init__.py", line 8, in <module>
    from . import importer
  File "/home/jx/.local/share/Anki2/addons21/Memrise_Course_Importer/importer.py", line 840
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax
```

And then realized on Arch Linux the newest Anki (v. 2.1.x) is automatically installed. Apparently the plugin doesn't work in Python 3. Had to install Anki 2.0.x to make it work.

Is there any plan now to support v. 2.1.x or is that currently not a priority and would wait until the new version sees wide adoption etc.? Guess this is a common problem with Python-based apps.

**Comment by Neribr** [comment]
anki 2.1 was a mistake, stick to 2.0

**Comment by x-ji** [comment]
Sure. That's a way to look at it...

**Comment by wilddom** [comment]
I will support 2.1 as soon as it comes out of beta.
See here:
https://anki.tenderapp.com/kb/anki-ecosystem/arch-linux-has-packaged-an-alpha-build-that-could-cause-data-loss

**Comment by x-ji** [comment]
Makes sense.

**Comment by jostyee** [comment]
@wilddom Anki 2.1 has been released, hope this plugin can be updated too.

**Comment by wilddom** [comment]
Unfortunately I'm too busy with other stuff at the moment, sorry...

**Comment by jostyee** [comment]
no problem, take your time.

**Comment by Fledron** [comment]
I don't know Python, but many other languages. So how different is the old Python from the new? If it is similar to the old one and only a few changes are needed maybe I can do it, programming languages are easy to learn if you already know a lot of them

**Comment by aTTocs** [comment]
I did a lot of the dirty work of porting to Anki 2.1, but then hit the limit of my abilities. If anyone is interested in going further, please take a look at my fork: aTTocs / memrise2anki-extension.

I got it to load cleanly into Anki, ran the 'Import Memrise Course...' menu item, entered username and password, clicked OK, and the resulting error ended with this:
  File "(path to Anki2)\Anki2\addons21\MemriseToAnki\Memrise_Course_Importer\memrise.py", line 715, in read
    return response.read_savedoriginal(n)
  File "http\client.py", line 448, in read
<class 'ValueError'>: negative count

**Comment by wilddom** [comment]
You can try the anki21 branch. But it's not thoroughly tested, so there may be still some bugs left...

**Comment by aTTocs** [comment]
It worked for me without any problems that I could detect.

Thanks!!
