### ISSUE TITLE
Button ok grey

### ISSUE THREAD

**Issue by Camethyleabergen** [wilddom/memrise2anki-extension#63]
Hi,

thank you for your amazing work, I'm eager to try it, unfortunately it seems that the OK button remains grey whatever option or URL I put in.. What do I do wrong? :)

Best

**Comment by wilddom** [comment]
Entering a valid memrise course urls in the form `https://www.memrise.com/course/[id]/[title]/` should enable the OK button. At least that's what it does when testing with Anki 2.0.50.

**Comment by Camethyleabergen** [comment]
Now it does, but yesterday with the same URL it didn't. 

Thank you very much ++
