### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by gri1n** [wilddom/memrise2anki-extension#65]
After realising that this add-on doesn't work with Anki 2.1.x I did a clean install of Anki 2.0. Unfortunately I can't get it the add-on to work. After installing the add-on it shows up in add-ons folder but no menu item appears in the Tools menu.

What could be wrong? Do you know when the add-on will be updated for 2.1.x?

**Comment by wilddom** [comment]
Sorry, I didn't have time to look into this, but I just pushed an update for Anki 2.1
