### ISSUE TITLE
Unable to install Add-on.

### ISSUE THREAD

**Issue by jarmanso7** [wilddom/memrise2anki-extension#67]
Good morning,

I'm completely new to Anki. I decided to switch it from Memrise as they announced that [user-created courses are to be moved away from Memrise mobile App](https://www.memrise.com/decks-by-memrise/). For that, I intend to use your tool to migrate my already existing Memrise courses to Anki 2.1

I Installed the latest release of Anki (version 2.1.9-standard) but I can't figure out the way to install the Add-on either via "Add-on" Go to Tools -> Add-Ons -> Browse & Install... or "Manually": Click on Tools -> Add-ons -> Open Add-ons Folder...". These options are not available in the Anki user interface.

Please, can you let me know what particular release of Anki are you running the Add-on against so I can try to get it to work with that release? I suspect the Addon is not compatible yet with the latest released on Anki based on this [closed issue](https://github.com/wilddom/memrise2anki-extension/issues/65).

Thank you very much for your help!

**Comment by thetrime** [comment]
For me (in 2.1.9-standard on macOS) it was Tools -> Add Ons -> View Files

Then extract the zip file into that folder. That did the trick for me.

**Comment by wilddom** [comment]
The instructions should be accurate now
