### ISSUE TITLE
Bug when attempting import

### ISSUE THREAD

**Issue by evanSpendlove** [wilddom/memrise2anki-extension#68]
Anki 2.1, Mac 10.13.6 (High Sierra)

Installed plugin as per instructions, tried to import memrise course.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.9 (ae67c976) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: memrise2anki-extension-master

Caught exception:
  File "/Users/Evan/Library/Application Support/Anki2/addons21/memrise2anki-extension-master/importer.py", line 968, in startCourseImporter
    if memriseService.isLoggedIn() or MemriseLoginDialog.login(memriseService):
  File "/Users/Evan/Library/Application Support/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 764, in isLoggedIn
    response = self.openWithRetry(request)
  File "/Users/Evan/Library/Application Support/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 752, in openWithRetry
    return self.opener.open(url)
  File "urllib/request.py", line 526, in open
  File "urllib/request.py", line 544, in _open
  File "urllib/request.py", line 504, in _call_chain
  File "/Users/Evan/Library/Application Support/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 731, in https_open
    return self.do_open_wrapped(http.client.HTTPSConnection, req, context=self._context, check_hostname=self._check_hostname)
  File "/Users/Evan/Library/Application Support/Anki2/addons21/memrise2anki-extension-master/memrise.py", line 721, in do_open_wrapped
    response = self.do_open(http_class, req, **http_conn_args)
  File "urllib/request.py", line 1320, in do_open
<class 'urllib.error.URLError'>: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>

**Comment by wilddom** [comment]
Okay, that's a tricky one, but it's actually not a bug of the addon.

Here you'll find instructions on how to solve this:

- http://www.cdotson.com/2017/01/sslerror-with-python-3-6-x-on-macos-sierra/
- https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore/42107877#42107877
- https://anki.tenderapp.com/discussions/add-ons/21737-quizlet-to-anki-converter-not-working-for-both-versions-anki-20-and-21-for-mac

**Comment by samuelfullerthomas** [comment]
Just for future people - to install on MacOS:

1. [download Python 3.6.7 ](https://www.python.org/downloads/release/python-367/)
2. run the installer and follow the instructions
3. once installed, open the Python3.6 application folder (in your Applications folder) and double click on the file `Install Certificates.command`. That'll run some commands that install some certs.

The gif below shows step 3.

![step 3 gif](https://user-images.githubusercontent.com/10165959/53102090-ef368a80-3522-11e9-9f65-9f34bc25d077.gif)

4. either restart anki (if you've install the add on) or install the add on and restart anki.

**Comment by mjhaxby** [comment]
I'm also having the issue, but I have gone through the whole process of installing the certificates with Python 3.6. I've restarted multiple times and even reinstalled it.

I notice that the version of python I have installed is 3.7.2, but the version that Anki is using is 3.6.7. I assume it has something to do with this?

**Comment by HollyGates** [comment]
Same for me - had to install Python 3.6.7 and run the certificates script, then memrise2anki add on works
