### ISSUE TITLE
No cards

### ISSUE THREAD

**Issue by beefpizza** [wilddom/memrise2anki-extension#73]
I am running Windows 10 Home. I installed Anki 2.1, downloaded the zip file, extracted it, and pasted the folder memrise2anki-extension-master into AppData>Roaming>Anki2>addons21, then restarted Anki.  I went into "Import Memrise Course," entered my username and password, inserted a URL to a course. The download took several minutes and showed my progress. Then I was taken through a series of options and chose the Basic/default options. 

When I get to the Anki screen, I see the course name, but there are NO CARDS.  I tried this with a course I had progress in and a course I never started.  I can't do a custom study. It is stuck at "Increase today's new card limit by **0** cards."  I can't increase the number above 0.  When I browse the decks, there is nothing in the cards. 

I'm not getting an actual error message though!

It's strange because when the course is downloading, it says "X/XXcards" and it also gives a sample card with the first line from the course.

I would really appreciate any help.  You must be inundated with questions these days! 

![nocards](https://user-images.githubusercontent.com/48110036/53609959-395ce300-3b97-11e9-96eb-854373238e7e.JPG)

**Comment by wilddom** [comment]
Hm... did you have a look in the card browser?

**Comment by beefpizza** [comment]
I tried that, but there was nothing in the card browser either.

I seem to have stumbled onto a solution, though... after importing the course, at "Select note type for newly imported notes," if I leave it "create new" instead of selecting "Basic" as I had been, it does work. The only think that doesn't quite work is the mems. The pictures didn't download (not sure if they were supposed to?) and the text of them has weird formatting. Not sure if I should open a new issue for that?

In any case, thanks for such a useful tool.

**Comment by wilddom** [comment]
Importing mems should be fixed now
