### ISSUE TITLE
Adon Error

### ISSUE THREAD

**Issue by TowelSniffer** [wilddom/memrise2anki-extension#78]
Addon has stopped working and is giving this error ;

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

**Comment by pasovsky** [comment]
@TowelSniffer check out https://stackoverflow.com/questions/49183801/ssl-certificate-verify-failed-with-urllib

**Comment by wilddom** [comment]
See #68
