### ISSUE TITLE
Scrape/download the Speak like a local section too

### ISSUE THREAD

**Issue by JasoonS** [wilddom/memrise2anki-extension#79]
It would be great to allow export of the "speak like a local" sections on the 'Official' language courses. I think this is only available to paying memrise customers, and also only on the major world languages.

It also might be difficult since each phrase often has multiple "speak like a local" video clips.
As a first step it could just fetch one per recording, and that should be enough.

Interested to hear if this has been in your thoughts?

**Comment by wilddom** [comment]
See #58
