### ISSUE TITLE
I downloaded a community created lesson and the audio did not pull. Will Memrise2Anki pull audio for community lessons. 

### ISSUE THREAD

**Issue by LevantineAspirations** [wilddom/memrise2anki-extension#81]
The lesson is here:

https://www.memrise.com/course/1509572/beginners-syrian-arabic/

My version of Anki is Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3

**Comment by wilddom** [comment]
Yes it does, just checked. The smoothest way is to let the addon create a new note type when importing and don't touch the field mapping.
