### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by Qaspar** [wilddom/memrise2anki-extension#85]
Upon login I get the message "Invalid credentials". It worked just fine last week. 

Upon second try I get this:

Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-05 12:14:12
Caught exception:
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\memrise2anki-extension\importer.py", line 214, in accept
    if self.memriseService.login(self.usernameLineEdit.text(),self.passwordLineEdit.text()):
  File "C:\Users\XXX\AppData\Roaming\Anki2\addons21\memrise2anki-extension\memrise.py", line 770, in login
    for field in form.find_all("input"):
AttributeError: 'NoneType' object has no attribute 'find_all'

My credentials are not invalid, nor did I type my login info wrong. My pro subscription runs out in a few days.

**Comment by bprosr12** [comment]
I also get the same issue.

**Comment by gordonmaloney** [comment]
Me too! I've used the extension a lot in the past and I've never had any problem with it.

**Comment by drsavage66** [comment]
Same here, I thought my computer updated something, and I tried reinstalling.

**Comment by Marcel4429** [comment]
I get the same issue.

**Comment by Qaspar** [comment]
Works like a charm. Just in time. Thank you very much!

**Comment by wilddom** [comment]
Thank you guys @Marcel4429 and @realmayus for the pull request
