### ISSUE TITLE
Issure Importing Course

### ISSUE THREAD

**Issue by nikkovc** [wilddom/memrise2anki-extension#93]
I have successfully downloaded many memrise courses using this add on and it is awesome, but for some reason an error is thrown when I try to download certain courses such as
https://app.memrise.com/course/2020826/japanese-0/3/?action=next
https://app.memrise.com/course/2022732/japanese-1/
https://app.memrise.com/course/1137112/kanji-japanese-core-1000-1000-most-common/
Here is an image of the error message:
![image](https://user-images.githubusercontent.com/42561764/98525180-1e84b200-2246-11eb-96f2-187203fdf24f.png)

These are some of the most popular japanese courses on memrise, so I imagine other people are having similiar issues.

**Comment by nikkovc** [comment]
It turns out the reason for the error is likely the grammar lessons that memrise added to some of their prebuilt courses. I attached a picture of an example of this. The Japanese 0 and 1 decks only import the words leading up to these. I think this add on is trying to take a media type from memrise that exists in these grammar lessons that is not support by Anki. Is it possible to have the add on skip these levels? I doubt anyone using Anki is interested in these, but they prevent the media in the levels that follow from being imported.
![image](https://user-images.githubusercontent.com/42561764/98739181-eaf57500-2376-11eb-98c4-96e9a89bdd8b.png)

**Comment by wilddom** [comment]
I think this could be the same as #91, #84 and #88, please try the latest [1.2.4](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.4) release.

**Comment by nikkovc** [comment]
I thought I had the latest release, but I will redownload it and try again

**Comment by nikkovc** [comment]
I redownloaded the latest release from the link you provided, but I still get the same error. I have been able to import all the other courses I wanted to except Japanese 0 (https://app.memrise.com/course/2020826/japanese-0/) and Japanese 1 (https://app.memrise.com/course/2022732/japanese-1/). Japanese 0 almost always stops importing after 7 cards and throws the error in the screenshot below.
![image](https://user-images.githubusercontent.com/42561764/98830949-fabd9980-2408-11eb-863d-3a130ed53626.png)

**Comment by nikkovc** [comment]
Thank you for maintaining the repository btw. I have found this add on to be very helpful

**Comment by wilddom** [comment]
Imported both courses works flawlessly here. Did you maybe select the note type which had been created by the old version of the addon?

**Comment by nikkovc** [comment]
I tried allowing the add on to generate it's own note type and using several of my own note types that worked fine for the Japanese 2-7 courses

**Comment by nikkovc** [comment]
I usually select "new note type" I also delete the note types generated by the add on after they are unused and don't select them as the note type for import.

**Comment by nikkovc** [comment]
Sorry about the spam. I also just download a fresh version of Anki (no other add-ons completely vanilla) on my friend's computer and installed the latest release and the same error occurred when I tried to import Japanese 0.

**Comment by nikkovc** [comment]
I usually select "new note type" I also delete the note types generated by the add on after they are unused and don't select them as the note type for import.

**Comment by nikkovc** [comment]
I download a fresh version of Anki on my friend's laptop (version 2.1.35 with no other add-ons) and installed the latest release of this add on, but I got the same error when I tried to download Japanese 0. Do you think it is a versioning issue?

**Comment by wilddom** [comment]
Is still had Anki 2.1.26. As of now I don't really understand what has changed, but I think I found at least a workaround, please try the [1.2.5](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.5) release.

**Comment by nikkovc** [comment]
Thank you! The new release worked flawlessly.
