### ISSUE TITLE
Answers containing `<Something>` are trimmed

### ISSUE THREAD

**Issue by fenuks** [wilddom/memrise2anki-extension#96]
It seems that there is a bug, if field looks like HTML tag.

I've converted [Vim Complete Command Reference](https://app.memrise.com/course/1534510/vim-complete-command-reference/) course, and if answer is a vim key, e.g. `<ESC>`, or `<CR>, it is removed from resulting Anki note. Answer `{char1}<BS>{char2}` is converted to `{char1} {char2}`.

I'm using the latest version of this extension, and Anki 2.1.53.

**Comment by wilddom** [comment]
Please try the [1.2.6](https://github.com/wilddom/memrise2anki-extension/releases/tag/v1.2.6) release.

**Comment by fenuks** [comment]
Thank you, problem is resolved.
